//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CounterRakaat_V2.Recource {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CounterRakaat_V2.Recource.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About us.
        /// </summary>
        internal static string About_menu {
            get {
                return ResourceManager.GetString("About_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на About us.
        /// </summary>
        internal static string About_table_of_contents {
            get {
                return ResourceManager.GetString("About_table_of_contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The Rakaat counter program was developed by IFox studio, which has been developing software, games, and 3D graphics since 2020..
        /// </summary>
        internal static string About_text {
            get {
                return ResourceManager.GetString("About_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Attention!.
        /// </summary>
        internal static string Alert_Attention {
            get {
                return ResourceManager.GetString("Alert_Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Please put your phone in your pants pockets.
        /// </summary>
        internal static string Alert_Put {
            get {
                return ResourceManager.GetString("Alert_Put", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contacts.
        /// </summary>
        internal static string Contacts_menu {
            get {
                return ResourceManager.GetString("Contacts_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Contacts.
        /// </summary>
        internal static string Contacts_table_of_contents {
            get {
                return ResourceManager.GetString("Contacts_table_of_contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Our mail - ilim11.net@gmail.com.
        /// </summary>
        internal static string Contacts_text_mail {
            get {
                return ResourceManager.GetString("Contacts_text_mail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Our website - https://theifox.com.
        /// </summary>
        internal static string Contacts_text_website {
            get {
                return ResourceManager.GetString("Contacts_text_website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на If you are ready for prayer, click Start..
        /// </summary>
        internal static string IfReady_main {
            get {
                return ResourceManager.GetString("IfReady_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Home.
        /// </summary>
        internal static string Main_menu {
            get {
                return ResourceManager.GetString("Main_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Menu.
        /// </summary>
        internal static string Menu_table_of_contents {
            get {
                return ResourceManager.GetString("Menu_table_of_contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Rakaat.
        /// </summary>
        internal static string Rakaat_main {
            get {
                return ResourceManager.GetString("Rakaat_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Table.
        /// </summary>
        internal static string Table_main {
            get {
                return ResourceManager.GetString("Table_main", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на How to use.
        /// </summary>
        internal static string Use_menu {
            get {
                return ResourceManager.GetString("Use_menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на How to use the program ?.
        /// </summary>
        internal static string Use_table_of_contents {
            get {
                return ResourceManager.GetString("Use_table_of_contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Using the Rakaat Counter program is very simple, for this you need to press the Start button and put your smartphone in your pants pockets. Next, the program itself will calculate the number of prayer rakaats you have made, after which you will see the result in the table. Also, if during the prayer you suddenly forget which rakaat you are on now, then you can simply click on the side button of the lock screen, and the program will vibrate the number of rakaats..
        /// </summary>
        internal static string Use_text {
            get {
                return ResourceManager.GetString("Use_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Why is this necessary?.
        /// </summary>
        internal static string Why_table_of_contents {
            get {
                return ResourceManager.GetString("Why_table_of_contents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Very often it happens that we forget how many cancers were made, and fall into doubts. The purpose of the program is to rid you of unwanted doubts..
        /// </summary>
        internal static string Why_text {
            get {
                return ResourceManager.GetString("Why_text", resourceCulture);
            }
        }
    }
}
